// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Assets.Logic.Editor.Templates
{
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ConditionTemplate : ConditionTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            this.Write("\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

	for (int i = 0; i < usingNamespaces.Length; ++i)
	{

            
            #line default
            #line hidden
            this.Write("\nusing ");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(usingNamespaces[i]));
            
            #line default
            #line hidden
            this.Write(";\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("\nusing System.Collections.Generic;\n#if UNITY_EDITOR\nusing System.Xml;\n#endif\n\nnam" +
                    "espace DigitalWorld.Logic\n{\n\t/// <summary>\n    /// ");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(desc));
            
            #line default
            #line hidden
            this.Write("\n    /// </summary>\n\tpublic partial class Condition");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" : BaseCondition\n\t{\n\t\t#region Common\n\t\tpublic override int Id\n\t\t{\n\t\t\tget\n\t\t\t{\n\t\t\t" +
                    "\treturn ");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(id));
            
            #line default
            #line hidden
            this.Write(";\n\t\t\t}\n\t\t}\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

		for (int i = 0; i < types.Length; ++i)
		{

            
            #line default
            #line hidden
            this.Write("\n\t\t/// <summary>\n        /// ");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(descripts[i]));
            
            #line default
            #line hidden
            this.Write("\n        /// </summary>\n\t\tpublic ");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(types[i]));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varNames[i]));
            
            #line default
            #line hidden
            this.Write(" = default(");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(types[i]));
            
            #line default
            #line hidden
            this.Write(");\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

		}

            
            #line default
            #line hidden
            this.Write("\n\t\tprivate enum EValueIndex\n\t\t{\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

		for (int i = 0; i < types.Length; ++i)
		{

            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varNames[i]));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(i));
            
            #line default
            #line hidden
            this.Write(", \n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

		}

            
            #line default
            #line hidden
            this.Write("\n\t\t}\n\n\t\tpublic Condition");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("()\n\t\t{\n\t\t\toperators = new ECheckOperator[");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(types.Length));
            
            #line default
            #line hidden
            this.Write("];\n\t\t}\n\t\t\n\t\tpublic override void OnAllocate()\n        {\n\t\t\tbase.OnAllocate();\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

			for (int i = 0; i < types.Length; ++i)
			{

            
            #line default
            #line hidden
            this.Write("\n\t\t\t");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varNames[i]));
            
            #line default
            #line hidden
            this.Write(" = default(");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(types[i]));
            
            #line default
            #line hidden
            this.Write(");\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("\t\t\t\n        }\n\n\t\tprotected override void OnRecycle()\n        {\n            base.O" +
                    "nRecycle();\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

			for (int i = 0; i < types.Length; ++i)
			{

            
            #line default
            #line hidden
            this.Write("\n\t\t\t");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varNames[i]));
            
            #line default
            #line hidden
            this.Write(" = default(");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(types[i]));
            
            #line default
            #line hidden
            this.Write(");\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("\n        }\n\n\t\tpublic override object Clone()\n        {\n            Condition");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" v = null;\n\t\t\tif (Application.isPlaying)\n            {\n\t\t\t\tv = ObjectPool<Conditi" +
                    "on");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">.Instance.Allocate();\n            }\n\t\t\telse\n\t\t\t{\n\t\t\t\tv = new Condition");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("();\n\t\t\t}\n\t\t\t\n\t\t\tif (null != v)\n\t\t\t{\n\t\t\t\tthis.CloneTo(v);\n\t\t\t}\n\t\t\t\n            ret" +
                    "urn v;\n        }\n\n\t\tpublic override T CloneTo<T>(T obj)\n        {\n            Co" +
                    "ndition");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" v = base.CloneTo(obj) as Condition");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(";\n            if (null != v)\n            {\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

				for (int i = 0; i < types.Length; ++i)
				{

            
            #line default
            #line hidden
            this.Write("\n\t\t\t\tv.");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varNames[i]));
            
            #line default
            #line hidden
            this.Write(" = this.");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varNames[i]));
            
            #line default
            #line hidden
            this.Write(";\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

				}

            
            #line default
            #line hidden
            this.Write(@"
            }
            return obj;
        }

		private ECheckOperator GetOper(EValueIndex index)
        {
            return GetOper((int)index);
        }
		#endregion

		#region Editor
#if UNITY_EDITOR
        private static Dictionary<string, string> descs = new Dictionary<string, string>();

        private static Dictionary<string, string> Descs
        {
            get
            {
                if (null == descs)
                    descs = new Dictionary<string, string>();

                if (descs.Count < 1)
                {
");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

		            for (int i = 0; i < varNames.Length; ++i)
		            {

            
            #line default
            #line hidden
            this.Write("\n                    descs.Add(\"");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varNames[i]));
            
            #line default
            #line hidden
            this.Write("\", \"");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(descripts[i]));
            
            #line default
            #line hidden
            this.Write("\");\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

		            }

            
            #line default
            #line hidden
            this.Write("\n                }\n\n                return descs;\n            }\n        }\n\n      " +
                    "  public override string Desc\n        {\n            get\n            {\n          " +
                    "      return \"");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(desc));
            
            #line default
            #line hidden
            this.Write(@""";
            }
        }

        protected override string GetFieldDesc(string fieldName)
        {
            Dictionary<string, string> descs = Descs;
            string v = string.Empty;
            descs.TryGetValue(fieldName, out v);
            return v;
        }

		protected override ECheckOperator GetOperatorFromField(string fieldName)
        {
            EValueIndex @enum = (EValueIndex)System.Enum.Parse(typeof(EValueIndex), fieldName);
			return GetOper((int)@enum);
        }

        protected override void SetOperatorByField(string fieldName, ECheckOperator oper)
        {
            bool ret = System.Enum.TryParse<EValueIndex>(fieldName, true, out EValueIndex retV);
            if (ret)
            {
                int index = (int)retV;
                SetOper(index, oper);
            }
        }

		protected override string GetOperKey(int index)
        {
            EValueIndex i = (EValueIndex)index;
            return i.ToString();
        }
#endif
		#endregion

		#region Serialization
		public override void OnEncode(byte[] buffer, int pos)
        {
            base.OnEncode(buffer, pos);
");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

			for (int i = 0; i < types.Length; ++i)
			{

            
            #line default
            #line hidden
            this.Write("\n\t\t\t");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(serializeFuncs[i]));
            
            #line default
            #line hidden
            this.Write("(this.");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varNames[i]));
            
            #line default
            #line hidden
            this.Write(");\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("          \n        }\n\n        public override void OnDecode(byte[] buffer, int po" +
                    "s)\n        {\n            base.OnDecode(buffer, pos);\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

			for (int i = 0; i < types.Length; ++i)
			{

            
            #line default
            #line hidden
            this.Write("\n\t\t\t");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deserializeFuncs[i]));
            
            #line default
            #line hidden
            this.Write("(ref this.");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varNames[i]));
            
            #line default
            #line hidden
            this.Write(");\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("\n        }\n\n#if UNITY_EDITOR\n        public override void OnDecode(XmlElement nod" +
                    "e)\n        {\n            base.OnDecode(node);\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

			for (int i = 0; i < types.Length; ++i)
			{

            
            #line default
            #line hidden
            this.Write("\n\t\t\tif (node.HasAttribute(\"");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varNames[i]));
            
            #line default
            #line hidden
            this.Write("\"))\n\t\t\t\t");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varNames[i]));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varLoadXmls[i]));
            
            #line default
            #line hidden
            this.Write(";\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("\n        }\n\n        public override void OnEncode(XmlElement node)\n        {\n\t\t\tb" +
                    "ase.OnEncode(node);\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

			for (int i = 0; i < types.Length; ++i)
			{

            
            #line default
            #line hidden
            this.Write("\n\t\t\tnode.SetAttribute(\"");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varNames[i]));
            
            #line default
            #line hidden
            this.Write("\", ");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(varWriteXmls[i]));
            
            #line default
            #line hidden
            this.Write(");\n");
            
            #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

			}

            
            #line default
            #line hidden
            this.Write("\n        }\n#endif\n\t\t#endregion\n\t}\n}\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\ConditionTemplate.tt"

private string _classNameField;

/// <summary>
/// Access the className parameter of the template.
/// </summary>
private string className
{
    get
    {
        return this._classNameField;
    }
}

private string[] _baseTypesField;

/// <summary>
/// Access the baseTypes parameter of the template.
/// </summary>
private string[] baseTypes
{
    get
    {
        return this._baseTypesField;
    }
}

private string[] _typesField;

/// <summary>
/// Access the types parameter of the template.
/// </summary>
private string[] types
{
    get
    {
        return this._typesField;
    }
}

private string[] _varNamesField;

/// <summary>
/// Access the varNames parameter of the template.
/// </summary>
private string[] varNames
{
    get
    {
        return this._varNamesField;
    }
}

private string[] _descriptsField;

/// <summary>
/// Access the descripts parameter of the template.
/// </summary>
private string[] descripts
{
    get
    {
        return this._descriptsField;
    }
}

private string[] _defaultValuesField;

/// <summary>
/// Access the defaultValues parameter of the template.
/// </summary>
private string[] defaultValues
{
    get
    {
        return this._defaultValuesField;
    }
}

private string[] _varWriteXmlsField;

/// <summary>
/// Access the varWriteXmls parameter of the template.
/// </summary>
private string[] varWriteXmls
{
    get
    {
        return this._varWriteXmlsField;
    }
}

private string[] _varLoadXmlsField;

/// <summary>
/// Access the varLoadXmls parameter of the template.
/// </summary>
private string[] varLoadXmls
{
    get
    {
        return this._varLoadXmlsField;
    }
}

private int _idField;

/// <summary>
/// Access the id parameter of the template.
/// </summary>
private int id
{
    get
    {
        return this._idField;
    }
}

private string _descField;

/// <summary>
/// Access the desc parameter of the template.
/// </summary>
private string desc
{
    get
    {
        return this._descField;
    }
}

private string[] _usingNamespacesField;

/// <summary>
/// Access the usingNamespaces parameter of the template.
/// </summary>
private string[] usingNamespaces
{
    get
    {
        return this._usingNamespacesField;
    }
}

private string[] _serializeFuncsField;

/// <summary>
/// Access the serializeFuncs parameter of the template.
/// </summary>
private string[] serializeFuncs
{
    get
    {
        return this._serializeFuncsField;
    }
}

private string[] _deserializeFuncsField;

/// <summary>
/// Access the deserializeFuncs parameter of the template.
/// </summary>
private string[] deserializeFuncs
{
    get
    {
        return this._deserializeFuncsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool classNameValueAcquired = false;
if (this.Session.ContainsKey("className"))
{
    this._classNameField = ((string)(this.Session["className"]));
    classNameValueAcquired = true;
}
if ((classNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("className");
    if ((data != null))
    {
        this._classNameField = ((string)(data));
    }
}
bool baseTypesValueAcquired = false;
if (this.Session.ContainsKey("baseTypes"))
{
    this._baseTypesField = ((string[])(this.Session["baseTypes"]));
    baseTypesValueAcquired = true;
}
if ((baseTypesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("baseTypes");
    if ((data != null))
    {
        this._baseTypesField = ((string[])(data));
    }
}
bool typesValueAcquired = false;
if (this.Session.ContainsKey("types"))
{
    this._typesField = ((string[])(this.Session["types"]));
    typesValueAcquired = true;
}
if ((typesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("types");
    if ((data != null))
    {
        this._typesField = ((string[])(data));
    }
}
bool varNamesValueAcquired = false;
if (this.Session.ContainsKey("varNames"))
{
    this._varNamesField = ((string[])(this.Session["varNames"]));
    varNamesValueAcquired = true;
}
if ((varNamesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("varNames");
    if ((data != null))
    {
        this._varNamesField = ((string[])(data));
    }
}
bool descriptsValueAcquired = false;
if (this.Session.ContainsKey("descripts"))
{
    this._descriptsField = ((string[])(this.Session["descripts"]));
    descriptsValueAcquired = true;
}
if ((descriptsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("descripts");
    if ((data != null))
    {
        this._descriptsField = ((string[])(data));
    }
}
bool defaultValuesValueAcquired = false;
if (this.Session.ContainsKey("defaultValues"))
{
    this._defaultValuesField = ((string[])(this.Session["defaultValues"]));
    defaultValuesValueAcquired = true;
}
if ((defaultValuesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("defaultValues");
    if ((data != null))
    {
        this._defaultValuesField = ((string[])(data));
    }
}
bool varWriteXmlsValueAcquired = false;
if (this.Session.ContainsKey("varWriteXmls"))
{
    this._varWriteXmlsField = ((string[])(this.Session["varWriteXmls"]));
    varWriteXmlsValueAcquired = true;
}
if ((varWriteXmlsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("varWriteXmls");
    if ((data != null))
    {
        this._varWriteXmlsField = ((string[])(data));
    }
}
bool varLoadXmlsValueAcquired = false;
if (this.Session.ContainsKey("varLoadXmls"))
{
    this._varLoadXmlsField = ((string[])(this.Session["varLoadXmls"]));
    varLoadXmlsValueAcquired = true;
}
if ((varLoadXmlsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("varLoadXmls");
    if ((data != null))
    {
        this._varLoadXmlsField = ((string[])(data));
    }
}
bool idValueAcquired = false;
if (this.Session.ContainsKey("id"))
{
    this._idField = ((int)(this.Session["id"]));
    idValueAcquired = true;
}
if ((idValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("id");
    if ((data != null))
    {
        this._idField = ((int)(data));
    }
}
bool descValueAcquired = false;
if (this.Session.ContainsKey("desc"))
{
    this._descField = ((string)(this.Session["desc"]));
    descValueAcquired = true;
}
if ((descValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("desc");
    if ((data != null))
    {
        this._descField = ((string)(data));
    }
}
bool usingNamespacesValueAcquired = false;
if (this.Session.ContainsKey("usingNamespaces"))
{
    this._usingNamespacesField = ((string[])(this.Session["usingNamespaces"]));
    usingNamespacesValueAcquired = true;
}
if ((usingNamespacesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("usingNamespaces");
    if ((data != null))
    {
        this._usingNamespacesField = ((string[])(data));
    }
}
bool serializeFuncsValueAcquired = false;
if (this.Session.ContainsKey("serializeFuncs"))
{
    this._serializeFuncsField = ((string[])(this.Session["serializeFuncs"]));
    serializeFuncsValueAcquired = true;
}
if ((serializeFuncsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("serializeFuncs");
    if ((data != null))
    {
        this._serializeFuncsField = ((string[])(data));
    }
}
bool deserializeFuncsValueAcquired = false;
if (this.Session.ContainsKey("deserializeFuncs"))
{
    this._deserializeFuncsField = ((string[])(this.Session["deserializeFuncs"]));
    deserializeFuncsValueAcquired = true;
}
if ((deserializeFuncsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("deserializeFuncs");
    if ((data != null))
    {
        this._deserializeFuncsField = ((string[])(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ConditionTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
