// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Assets.Logic.Editor.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class PropertyStandardTemplate : PropertyStandardTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            
            #line 18 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tips));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 19 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"

	for (int i = 0; i < usingNamespaces.Length; ++i)
	{

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 23 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(usingNamespaces[i]));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 24 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"

	}

            
            #line default
            #line hidden
            this.Write("#if UNITY_EDITOR\r\nusing System.Xml;\r\n#endif\r\n\r\nnamespace ");
            
            #line 31 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(namespaceName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t/// <summary>\r\n    /// ");
            
            #line 34 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(desc));
            
            #line default
            #line hidden
            this.Write("\r\n    /// </summary>\r\n    public sealed partial class Property");
            
            #line 36 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" : PropertyTemplate<");
            
            #line 36 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(valueType));
            
            #line default
            #line hidden
            this.Write(">\r\n    {\r\n        public enum EPropertyModel\r\n        {\r\n");
            
            #line 40 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"

            for (int i = 0; i < modelNames.Length; ++i)
			{

            
            #line default
            #line hidden
            this.Write("            /// <summary>\r\n            /// ");
            
            #line 45 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelDescs[i]));
            
            #line default
            #line hidden
            this.Write("\r\n            /// </summary>        \r\n            ");
            
            #line 47 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNames[i]));
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 48 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"

            }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        #region Params\r\n        public override int Id => ");
            
            #line 54 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(id));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n        public override ");
            
            #line 56 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(valueType));
            
            #line default
            #line hidden
            this.Write(" Value\r\n        {\r\n            get => _value;\r\n            set => _value = value;" +
                    "\r\n        }\r\n        private ");
            
            #line 61 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(valueType));
            
            #line default
            #line hidden
            this.Write(" _value;\r\n        #endregion\r\n\r\n        #region Model\r\n        public static Prop" +
                    "ertyTemplate<");
            
            #line 65 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(valueType));
            
            #line default
            #line hidden
            this.Write("> AllocateProperty(EPropertyModel model)\r\n        {\r\n            switch (model)\r\n" +
                    "            {\r\n");
            
            #line 69 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"

                for (int i = 0; i < modelNames.Length; ++i)
                {

            
            #line default
            #line hidden
            this.Write("                case EPropertyModel.");
            
            #line 73 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNames[i]));
            
            #line default
            #line hidden
            this.Write(":\r\n                {\r\n                    if (Application.isPlaying)\r\n           " +
                    "         {\r\n                        return ObjectPool<Property");
            
            #line 77 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNames[i]));
            
            #line default
            #line hidden
            this.Write(">.Instance.Allocate();\r\n                    }\r\n                    return new Pro" +
                    "perty");
            
            #line 79 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelNames[i]));
            
            #line default
            #line hidden
            this.Write("();\r\n                }\r\n");
            
            #line 81 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"

                }

            
            #line default
            #line hidden
            this.Write("                default:\r\n                {\r\n                    if (Application." +
                    "isPlaying)\r\n                    {\r\n                        return ObjectPool<Pro" +
                    "perty");
            
            #line 88 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">.Instance.Allocate();\r\n                    }\r\n                    return new Pro" +
                    "perty");
            
            #line 90 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("();\r\n                }\r\n            }\r\n        }\r\n        #endregion\r\n\r\n        #" +
                    "region Clone\r\n        public override object Clone()\r\n        {\r\n            Pro" +
                    "perty");
            
            #line 99 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(" v = null;\r\n            if (Application.isPlaying)\r\n            {\r\n              " +
                    "  v = Dream.Core.ObjectPool<Property");
            
            #line 102 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(">.Instance.Allocate();\r\n            }\r\n            else\r\n            {\r\n         " +
                    "       v = new Property");
            
            #line 106 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(@"();
            }

            if (null != v)
            {
                this.CloneTo(v);
            }

            return v;
        }

        public override TObj CloneTo<TObj>(TObj obj)
        {
            if (base.CloneTo(obj) is Property");
            
            #line 119 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write(@" p)
            {
                p._value = this._value;
            }
            return obj;
        }
        #endregion

        #region Serialization
        protected override void OnCalculateSize()
        {
            base.OnCalculateSize();

            ");
            
            #line 132 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(calculateFunc));
            
            #line default
            #line hidden
            this.Write("(this._value);\r\n        }\r\n\r\n        protected override void OnEncode()\r\n        " +
                    "{\r\n            base.OnEncode();\r\n\r\n            ");
            
            #line 139 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(serializeFunc));
            
            #line default
            #line hidden
            this.Write("(this._value);\r\n        }\r\n\r\n        protected override void OnDecode()\r\n        " +
                    "{\r\n            base.OnDecode();\r\n\r\n            ");
            
            #line 146 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deserializeFunc));
            
            #line default
            #line hidden
            this.Write("(ref this._value);\r\n        }\r\n\r\n#if UNITY_EDITOR\r\n        protected override voi" +
                    "d OnEncode(XmlElement element)\r\n        {\r\n            base.OnEncode(element);\r\n" +
                    "\r\n            ");
            
            #line 154 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(serializeFunc));
            
            #line default
            #line hidden
            this.Write("(this._value, \"_value\");\r\n            \r\n        }\r\n\r\n        protected override v" +
                    "oid OnDecode(XmlElement element)\r\n        {\r\n            base.OnDecode(element);" +
                    "\r\n\r\n            ");
            
            #line 162 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(deserializeFunc));
            
            #line default
            #line hidden
            this.Write("(ref this._value, \"_value\");\r\n        }\r\n#endif\r\n        #endregion\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\Projects\DigitalWorld\DigitalWorld\Assets\Logic\Editor\Templates\PropertyStandardTemplate.tt"

private string _classNameField;

/// <summary>
/// Access the className parameter of the template.
/// </summary>
private string className
{
    get
    {
        return this._classNameField;
    }
}

private string _valueTypeField;

/// <summary>
/// Access the valueType parameter of the template.
/// </summary>
private string valueType
{
    get
    {
        return this._valueTypeField;
    }
}

private int _idField;

/// <summary>
/// Access the id parameter of the template.
/// </summary>
private int id
{
    get
    {
        return this._idField;
    }
}

private string _descField;

/// <summary>
/// Access the desc parameter of the template.
/// </summary>
private string desc
{
    get
    {
        return this._descField;
    }
}

private string[] _usingNamespacesField;

/// <summary>
/// Access the usingNamespaces parameter of the template.
/// </summary>
private string[] usingNamespaces
{
    get
    {
        return this._usingNamespacesField;
    }
}

private string _namespaceNameField;

/// <summary>
/// Access the namespaceName parameter of the template.
/// </summary>
private string namespaceName
{
    get
    {
        return this._namespaceNameField;
    }
}

private string _serializeFuncField;

/// <summary>
/// Access the serializeFunc parameter of the template.
/// </summary>
private string serializeFunc
{
    get
    {
        return this._serializeFuncField;
    }
}

private string _deserializeFuncField;

/// <summary>
/// Access the deserializeFunc parameter of the template.
/// </summary>
private string deserializeFunc
{
    get
    {
        return this._deserializeFuncField;
    }
}

private string _calculateFuncField;

/// <summary>
/// Access the calculateFunc parameter of the template.
/// </summary>
private string calculateFunc
{
    get
    {
        return this._calculateFuncField;
    }
}

private string[] _modelNamesField;

/// <summary>
/// Access the modelNames parameter of the template.
/// </summary>
private string[] modelNames
{
    get
    {
        return this._modelNamesField;
    }
}

private string[] _modelDescsField;

/// <summary>
/// Access the modelDescs parameter of the template.
/// </summary>
private string[] modelDescs
{
    get
    {
        return this._modelDescsField;
    }
}

private string _tipsField;

/// <summary>
/// Access the tips parameter of the template.
/// </summary>
private string tips
{
    get
    {
        return this._tipsField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool classNameValueAcquired = false;
if (this.Session.ContainsKey("className"))
{
    this._classNameField = ((string)(this.Session["className"]));
    classNameValueAcquired = true;
}
if ((classNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("className");
    if ((data != null))
    {
        this._classNameField = ((string)(data));
    }
}
bool valueTypeValueAcquired = false;
if (this.Session.ContainsKey("valueType"))
{
    this._valueTypeField = ((string)(this.Session["valueType"]));
    valueTypeValueAcquired = true;
}
if ((valueTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("valueType");
    if ((data != null))
    {
        this._valueTypeField = ((string)(data));
    }
}
bool idValueAcquired = false;
if (this.Session.ContainsKey("id"))
{
    this._idField = ((int)(this.Session["id"]));
    idValueAcquired = true;
}
if ((idValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("id");
    if ((data != null))
    {
        this._idField = ((int)(data));
    }
}
bool descValueAcquired = false;
if (this.Session.ContainsKey("desc"))
{
    this._descField = ((string)(this.Session["desc"]));
    descValueAcquired = true;
}
if ((descValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("desc");
    if ((data != null))
    {
        this._descField = ((string)(data));
    }
}
bool usingNamespacesValueAcquired = false;
if (this.Session.ContainsKey("usingNamespaces"))
{
    this._usingNamespacesField = ((string[])(this.Session["usingNamespaces"]));
    usingNamespacesValueAcquired = true;
}
if ((usingNamespacesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("usingNamespaces");
    if ((data != null))
    {
        this._usingNamespacesField = ((string[])(data));
    }
}
bool namespaceNameValueAcquired = false;
if (this.Session.ContainsKey("namespaceName"))
{
    this._namespaceNameField = ((string)(this.Session["namespaceName"]));
    namespaceNameValueAcquired = true;
}
if ((namespaceNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("namespaceName");
    if ((data != null))
    {
        this._namespaceNameField = ((string)(data));
    }
}
bool serializeFuncValueAcquired = false;
if (this.Session.ContainsKey("serializeFunc"))
{
    this._serializeFuncField = ((string)(this.Session["serializeFunc"]));
    serializeFuncValueAcquired = true;
}
if ((serializeFuncValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("serializeFunc");
    if ((data != null))
    {
        this._serializeFuncField = ((string)(data));
    }
}
bool deserializeFuncValueAcquired = false;
if (this.Session.ContainsKey("deserializeFunc"))
{
    this._deserializeFuncField = ((string)(this.Session["deserializeFunc"]));
    deserializeFuncValueAcquired = true;
}
if ((deserializeFuncValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("deserializeFunc");
    if ((data != null))
    {
        this._deserializeFuncField = ((string)(data));
    }
}
bool calculateFuncValueAcquired = false;
if (this.Session.ContainsKey("calculateFunc"))
{
    this._calculateFuncField = ((string)(this.Session["calculateFunc"]));
    calculateFuncValueAcquired = true;
}
if ((calculateFuncValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("calculateFunc");
    if ((data != null))
    {
        this._calculateFuncField = ((string)(data));
    }
}
bool modelNamesValueAcquired = false;
if (this.Session.ContainsKey("modelNames"))
{
    this._modelNamesField = ((string[])(this.Session["modelNames"]));
    modelNamesValueAcquired = true;
}
if ((modelNamesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("modelNames");
    if ((data != null))
    {
        this._modelNamesField = ((string[])(data));
    }
}
bool modelDescsValueAcquired = false;
if (this.Session.ContainsKey("modelDescs"))
{
    this._modelDescsField = ((string[])(this.Session["modelDescs"]));
    modelDescsValueAcquired = true;
}
if ((modelDescsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("modelDescs");
    if ((data != null))
    {
        this._modelDescsField = ((string[])(data));
    }
}
bool tipsValueAcquired = false;
if (this.Session.ContainsKey("tips"))
{
    this._tipsField = ((string)(this.Session["tips"]));
    tipsValueAcquired = true;
}
if ((tipsValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("tips");
    if ((data != null))
    {
        this._tipsField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class PropertyStandardTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
