// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Assets.Tables.Editor.Templates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class TableManagerTemplate : TableManagerTemplateBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("using Dream.Core;\r\nusing Dream.Table;\r\n\r\nnamespace ");
            
            #line 12 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(namespaceName));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// 表格管理器\r\n    /// </summary>\r\n    public sealed part" +
                    "ial class TableManager : Singleton<TableManager>\r\n    {\r\n        #region Tables\r" +
                    "\n");
            
            #line 20 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

        for (int i = 0; i < tableNames.Length; ++i)
        {

            
            #line default
            #line hidden
            this.Write("        public ");
            
            #line 24 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableClassNames[i]));
            
            #line default
            #line hidden
            this.Write("Table ");
            
            #line 24 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableClassNames[i]));
            
            #line default
            #line hidden
            this.Write("Table { get; private set; } = new ");
            
            #line 24 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableClassNames[i]));
            
            #line default
            #line hidden
            this.Write("Table();\r\n");
            
            #line 25 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("        #endregion\r\n\r\n        #region Decode\r\n        public void Decode()\r\n     " +
                    "   {\r\n");
            
            #line 33 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

        for (int i = 0; i < tableNames.Length; ++i)
        {

            
            #line default
            #line hidden
            this.Write("           ");
            
            #line 37 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableClassNames[i]));
            
            #line default
            #line hidden
            this.Write("Table = this.ApplyDecodeTable<");
            
            #line 37 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableClassNames[i]));
            
            #line default
            #line hidden
            this.Write("Table>(\"");
            
            #line 37 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNames[i]));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 38 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        public void DecodeJson()\r\n        {\r\n");
            
            #line 45 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

        for (int i = 0; i < tableNames.Length; ++i)
        {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 49 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableClassNames[i]));
            
            #line default
            #line hidden
            this.Write("Table = this.ApplyDecodeTableWithJson<");
            
            #line 49 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableClassNames[i]));
            
            #line default
            #line hidden
            this.Write("Table>(\"");
            
            #line 49 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNames[i]));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 50 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write(@"        }

        private T ApplyDecodeTable<T>(string tableName) where T : class
        {
            return this.ProcessDecodeTable<T>(tableName);
        }

        private T ApplyDecodeTableWithJson<T>(string tableName) where T : class
        {
            return this.ProcessDecodeTableWithJson<T>(tableName);
        }
        #endregion

        #region Encode
        public void Encode()
        {
");
            
            #line 69 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

        for (int i = 0; i < tableNames.Length; ++i)
        {

            
            #line default
            #line hidden
            this.Write("            this.ApplyEncodeTable(");
            
            #line 73 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableClassNames[i]));
            
            #line default
            #line hidden
            this.Write("Table, \"");
            
            #line 73 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNames[i]));
            
            #line default
            #line hidden
            this.Write("\");\r\n");
            
            #line 74 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

        }

            
            #line default
            #line hidden
            this.Write(@"        }

        private void ApplyEncodeTable(object table, string tableName)
        {
            this.ProcessEncodeTable(table, tableName);
        }
        #endregion

        #region Utility
        public static ITable CreateTable(string tableName)
        {
            switch (tableName)
            {
");
            
            #line 90 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

                for (int i = 0; i < tableNames.Length; ++i)
                {

            
            #line default
            #line hidden
            this.Write("                case \"");
            
            #line 94 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNames[i]));
            
            #line default
            #line hidden
            this.Write("\":\r\n                    return new ");
            
            #line 95 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableClassNames[i]));
            
            #line default
            #line hidden
            this.Write("Table();\r\n");
            
            #line 96 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

                }

            
            #line default
            #line hidden
            this.Write("                default:\r\n                {\r\n                    return null;\r\n  " +
                    "              }\r\n            }\r\n        }\r\n\r\n        public static System.Type G" +
                    "etTableType(string tableName)\r\n        {\r\n            switch (tableName)\r\n      " +
                    "      {\r\n");
            
            #line 110 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

                for (int i = 0; i < tableNames.Length; ++i)
                {

            
            #line default
            #line hidden
            this.Write("                case \"");
            
            #line 114 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableNames[i]));
            
            #line default
            #line hidden
            this.Write("\":\r\n                    return typeof(");
            
            #line 115 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(tableClassNames[i]));
            
            #line default
            #line hidden
            this.Write("Table);\r\n");
            
            #line 116 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

                }

            
            #line default
            #line hidden
            this.Write("                default:\r\n                {\r\n                    return null;\r\n  " +
                    "              }\r\n            }\r\n        }\r\n        #endregion\r\n\r\n    }\r\n}\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 1 "D:\Projects\DigitalWorld\DigitalWorld\DigitalWorld\Assets\Tables\Editor\Templates\TableManagerTemplate.tt"

private string _namespaceNameField;

/// <summary>
/// Access the namespaceName parameter of the template.
/// </summary>
private string namespaceName
{
    get
    {
        return this._namespaceNameField;
    }
}

private string[] _tableNamesField;

/// <summary>
/// Access the tableNames parameter of the template.
/// </summary>
private string[] tableNames
{
    get
    {
        return this._tableNamesField;
    }
}

private string[] _tableClassNamesField;

/// <summary>
/// Access the tableClassNames parameter of the template.
/// </summary>
private string[] tableClassNames
{
    get
    {
        return this._tableClassNamesField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public virtual void Initialize()
{
    if ((this.Errors.HasErrors == false))
    {
bool namespaceNameValueAcquired = false;
if (this.Session.ContainsKey("namespaceName"))
{
    this._namespaceNameField = ((string)(this.Session["namespaceName"]));
    namespaceNameValueAcquired = true;
}
if ((namespaceNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("namespaceName");
    if ((data != null))
    {
        this._namespaceNameField = ((string)(data));
    }
}
bool tableNamesValueAcquired = false;
if (this.Session.ContainsKey("tableNames"))
{
    this._tableNamesField = ((string[])(this.Session["tableNames"]));
    tableNamesValueAcquired = true;
}
if ((tableNamesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("tableNames");
    if ((data != null))
    {
        this._tableNamesField = ((string[])(data));
    }
}
bool tableClassNamesValueAcquired = false;
if (this.Session.ContainsKey("tableClassNames"))
{
    this._tableClassNamesField = ((string[])(this.Session["tableClassNames"]));
    tableClassNamesValueAcquired = true;
}
if ((tableClassNamesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("tableClassNames");
    if ((data != null))
    {
        this._tableClassNamesField = ((string[])(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class TableManagerTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
